"""``tilefoundry.dsl`` — author-facing DSL surface.

This package exposes:

- :mod:`tilefoundry.dsl.tf` — HIR ops (``dialect="tf"``).
- :mod:`tilefoundry.dsl.T`  — TIR ops (``dialect="T"``).
- :class:`tilefoundry.dsl.Tensor` — DSL authoring-surface annotation
  sugar (parser-owned). ``Tensor[(M, K), "f32"]`` is a DSL
  type-annotation construct used by ``@func`` parameter / return
  hints; it is NOT the IR tensor type. The IR type carrier is
  :class:`tilefoundry.ir.types.TensorType`.

The two op sub-namespaces rely on a module-level ``__getattr__`` that
resolves names against the OpSchema registry on demand; ``__all__``
on each submodule lists the schema names so ``from tilefoundry.dsl.tf
import *`` brings every registered HIR op into the call site's
lexical scope. Static IDE completion is delivered via ``.pyi`` stubs
generated by :mod:`tilefoundry.dsl._stub_gen` (gitignored; regenerate
via ``python -m tilefoundry.dsl regen``).

DType values use **string form** in DSL source —
``Tensor[(8,), "bf16"]``, ``zeros((1, 64), "bf16", ...)`` — and the
parser auto-converts the string to the corresponding ``DType`` descriptor
at attribute-binding time.
"""

from __future__ import annotations

# ruff: noqa: I001 -- curated re-export order; alphabetical sort breaks staged imports.

from tilefoundry.dsl import tf, T
from tilefoundry.dsl._tensor import Tensor

# Authoring-surface re-exports. ``tilefoundry.dsl`` is the single
# authoring entry; users should not reach into
# ``tilefoundry.ir.core.kinds`` / ``tilefoundry.ir.types.shard.*`` for
# everyday DSL writing. Runtime API (``compile`` / ``jit`` / ``view``
# / ...) stays at top-level ``tilefoundry.*``; everything below is what
# an ``@func`` body needs.
from tilefoundry.script import func
from tilefoundry.ir.core.pattern import DimVarRangePat, Pattern
from tilefoundry.ir.types.dim import DimVar, ceildiv
from tilefoundry.ir.types.shard import (
    Mesh,
    Topology,
    Split,
    Partial,
    Broadcast,
    S,
    P,
    B,
)
from tilefoundry.ir.core.kinds import ReduceKind, UnaryKind, BinaryKind

__all__ = [
    "tf",
    "T",
    "Tensor",
    "func",
    "Pattern",
    "DimVarRangePat",
    "DimVar",
    "ceildiv",
    "Mesh",
    "Topology",
    "Split",
    "Partial",
    "Broadcast",
    "S",
    "P",
    "B",
    "ReduceKind",
    "UnaryKind",
    "BinaryKind",
]
